### PR TITLE
build: fix compile with python 3.10

### PR DESCRIPTION
**Pull request by aceforeverd**
- fix compile with python 3.10
  - resolved the import error: `cannot import name 'Mapping' from 'collections'`, by upgrade jinja version
- use python 3.10 as default python interrupter in macos job
   - it is default python2 in macos environment
   - python2 will not supported

### CODE REVIEW

**Comment by aceforeverd** [comment]
Not fixed. It seems it should upgrade protobuf version.
